version: "3.8"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    container_name: rails-example
    build: .
    command: "tail -f /dev/null"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
